{% set name = "librsync" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1a79a74173fe385bb59e6ff5be80ac33ab654f9fcc7a9beba37d875ecba88a39


build:
  skip: true  # [win]
  number: 0
  script: cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON . ; make install;

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]


test:
  commands:
    - ./checksum_test
    - ./hashtable_test
    - ./isprefix_test
    - ./netint_test
    - ./rollsum_test
    - ./sumset_test
  source_files:
    - checksum_test
    - hashtable_test
    - isprefix_test
    - netint_test
    - rollsum_test
    - sumset_test


about:
  home: https://github.com/librsync/librsync
  license: LGPL-2.1-only
  license_file: COPYING
  summary: A library for calculating and applying network deltas
  description: |
    librsync is a library for calculating and applying network deltas, with an interface designed to
    ease integration into diverse network applications.
  doc_url: https://librsync.github.io/
  dev_url: https://github.com/librsync/librsync

extra:
  recipe-maintainers:
    - kpalin
